version: "3.8"

services:
  tempo:
    image: grafana/tempo:2.2.2
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3110:3100"  # Tempo
      - "9411:9411"  # Zipkin

  loki:
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.46.0
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.1.0
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
  eureka-server:
    build:
      context: ./EurekaServer  # Chemin vers le dossier contenant le service Eureka
    ports:
      - "8761:8761"  # Port exposé par le service Eureka

  gestion-medecins:
    build:
      context: ./Service.de.Gestion.des.Medecins  # Chemin vers le service de gestion des médecins
    ports:
      - "8082:8082"  # Port exposé par le service de gestion des médecins

  gestion-patients:
    build:
      context: ./Service.de.Gestion.des.Patients  # Chemin vers le service de gestion des patients
    ports:
      - "8080:8080"  # Port exposé par le service de gestion des patients

  gestion-rendezvous:
    build:
      context: ./Service.de.Gestion.des.Rendez-vous  # Chemin vers le service de gestion des rendez-vous
    ports:
      - "8081:8081"  # Port exposé par le service de gestion des rendez-vous
